Desmo_class/Desmo_class/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from first_app import views
urlpatterns = [
    url(r'^',include('first_app.urls')),
    url(r'^admin/', admin.site.urls),
]

Desmo_class/first_app/urls.py
from django.conf.urls import url
from first_app import views

app_name = 'first_app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^help/$', views.help,name='help'),
    url(r'^users/$', views.user,name='user'),
    url(r'^reta/$', views.reta,name='reta'),
    url(r'^parabola/$', views.parabola,name='parabola'),
    url(r'^circulo/$', views.circulo,name='circulo'),
    url(r'^elipse/$', views.elipse,name='elipse'),
    url(r'^hiperbole/$', views.hiperbole,name='hiperbole'),
    url(r'^outros/$', views.outros,name='outros'),
    url(r'^trigonometria/$', views.trigonometria,name='trigonometria'),
    url(r'^formpage/$',views.form_name_view,name='form_page'),
]

Desmo_class/first_app/models.py
from django.db import models

class Resposta(models.Model):
    Num_Pergunta = models.IntegerField(unique=True)
    Resposta = models.IntegerField()

    def __str__(self):
        return str(self.Num_Pergunta)
        
class Users(models.Model):
    First_name = models.CharField(max_length=30)
    Last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=264,unique=True)

    def __str__(self):
        return str(self.email)
# Create your models here.

Desmo_class/first_app/forms.py
from django import forms
from first_app.models import Users
from django.core import validators

class NewUser(forms.ModelForm):
    class Meta():
        model = Users
        fields = '__all__'

class TesteSimples(forms.Form):
    resp = forms.IntegerField()
    botcatcher = forms.CharField(required=False,widget=forms.HiddenInput,validators=[validators.MaxLengthValidator(0)])

Desmo_class/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Users
from first_app import forms
from first_app.forms import NewUser

# Create your views here.
def index(request):
    return render(request,'first_app/index.html')
def help(request):
    help_dict = {'help_insert':'HELP!'}
    return render(request,'first_app/help.html',context=help_dict)
def user(request):
    form = NewUser()
    if request.method == "POST":
        form = NewUser(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')
    return render(request,'first_app/user.html',{"form":form})
def reta(request):
    CoefLinT1 = forms.TesteSimples()
    CoefAngT1 = forms.TesteSimples()
    return render(request,'first_app/reta.html',{'test1':CoefLinT1,'test2':CoefAngT1})
def parabola(request):
    return render(request,'first_app/parabola.html')
def circulo(request):
    return render(request,'first_app/circulo.html')
def elipse(request):
    return render(request,'first_app/elipse.html')
def hiperbole(request):
    return render(request,'first_app/hiperbole.html')
def outros(request):
    return render(request,'first_app/outros.html')
def trigonometria(request):
    return render(request,'first_app/trigonometria.html')
def form_name_view(request):
    form = forms.NewUser()
    return render(request,'first_app/form_page.html',{'form':form})

Desmo_class/templates/first_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>DESMOS CLASS</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "CSS/mystyle.css" %}>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Menu</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'first_app:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:reta' %}">Retas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:parabola' %}">Parábolas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:trigonometria' %}">Funções Trigonométricas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:circulo' %}">Circunferência</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:elipse' %}">Elipse</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:hiperbole' %}">Hipérbole</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:outros' %}">Extras</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:help' %}">Ajuda</a>
        </li>
      </ul>
    </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

Desmo_class/templates/first_app/circulo.html
<!DOCTYPE html>
{% extends "first_app/base.html"%}
{% block body_block%}
      <div class="jumbotron">
        <h1>Círculo</h1>
      </div>
  {% endblock %}

Desmo_class/templates/first_app/elipse.html
<!DOCTYPE html>
{% extends "first_app/base.html"%}
{% block body_block%}
      <div class="jumbotron">
        <h1>Elipse</h1>
      </div>
{% endblock %}

Desmo_class/templates/first_app/form_page.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <header>
      <a href="../">Voltar</a>
    </header>
    <h1>Fill out the form!</h1>
    <div class="container">
      <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>
  </body>
</html>

Desmo_class/templates/first_app/help.html
<!DOCTYPE html>
{% extends "first_app/base.html"%}
{% block body_block%}
      <div class="jumbotron">
        <h1>{{help_insert}}</h1>
        <h1>essa é a pagina de ajuda</h1>
      </div>
      <p>para qualquer problemas entre em contato com</p>
      <p><strong>Guilherme del rio</strong> @ delrio.guilherme@gmail.com</p>
{% endblock %}

Desmo_class/templates/first_app/hiperbole.html
<!DOCTYPE html>
{% extends "first_app/base.html"%}
{% block body_block%}
      <div class="jumbotron">
        <h1>Hipérbole</h1>
      </div>
{% endblock %}

Desmo_class/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html"%}
{% block body_block%}
      <div class="jumbotron">
        <h1>Bem-vindo ao Aplicativo de Auxilio ao DESMOS</h1>
      </div>
      <h1>Cadastre-se!</h1>
      <p>Para Cadastro: <a href="/users/">users</a></p>
      <h1>O que é o Aplicativo?</h1>
      <p>O aplicativo foi criado com o intuito de auxiliar na aprendizagem da calculadora DESMOS.<br>
      O App serve como um guia, ou um manual sobre cada função a ser utilizada nos desenhos.<br>
      É abordado as seguintes funções:</p>
      <ul>
        <li>Retas</li>
        <li>Parábolas</li>
        <li>Funções Trigonométricas</li>
        <li>Circunferências</li>
        <li>Elipses</li>
        <li>Hipérboles</li>
        <li>Outros</li>
      </ul>
{% endblock %}

Desmo_class/templates/first_app/outros.html
<!DOCTYPE html>
{% extends "first_app/base.html"%}
{% block body_block%}
      <div class="jumbotron">
        <h1>Extras</h1>
      </div>
{% endblock %}

Desmo_class/templates/first_app/parabola.html
<!DOCTYPE html>
{% extends "first_app/base.html"%}
{% block body_block%}
      <div class="jumbotron">
        <h1>Parábolas</h1>
      </div>
      <h2>O que são Parábolas?</h2>
      <p>Parabolas são curvas caracterizadas por uma função de <strong>segundo grau</strong>.<br>
      Elas são o utilizadas para dar curvas para nossos desenhos.<br>
      Veremos as formas de reprensentar e manipular as parábolas.<br>
      <em>"Gata me chama de Paul Walker e deixa eu fazer um drift nas suas curvas" - Michel Zeine,2016</em></p>
{% endblock %}

Desmo_class/templates/first_app/reta.html
<!DOCTYPE html>
{% extends "first_app/base.html"%}
{% block body_block%}
      <div class="jumbotron">
        <h1>Retas</h1>
      </div>
      <h2>O que são retas?</h2>
      <p>Retas são o tipo mais simples de <strong>Desenhos</strong> que existem na matematica.<br>
      Elas são essenciais para desenhar, do basico ao avançado.<br>
      Retas pode ser descritas a maioria das vezes por uma <strong>função polinomial do primeiro grau</strong><br>
      Também conhecida como <strong>função afim</strong> chamaremos ela desta forma de agora em diante.<br>
      <em>"com 5 ou 6 retas é facil fazer um castelo" - Toquinho,1980</em></p>
      <p><strong>Exemplo de Reta:</strong></p>
      <img src="https://i.imgur.com/IoiY64r.png" alt="OPS! Imagem não encontrada!">
      <small><br><em>formula: y = 2x+1</em></small>
      <h2>Função Afim</h2>
      <p>O gráfico da Função Afim é uma reta, e por manipular a função acabamos por manipular a reta <br>
      A função afim tem uma forma genérica de ser representada:<br>
      Esta é a forma genérica da função afim:<strong>y = a*x + b</strong><br>
      Onde <em><strong>a</strong></em> é chamado de coeficiente angular da reta<br>
      e <em><strong>b</strong></em> é chamado de coeficiente linear da reta.<br>
      então iremos ver qual a função de cada coeficiente, e como podemos <br>
      manipula-los para gerar nossos desenhos.</p>
      <p>Te encorajo a entrar no <a target="_blank" href="http://www.desmos.com">DESMOS</a> e seguir o passo a passo abaixo:</p>
      <p><strong>1</strong> entre no link acima <br>
      <strong>2</strong> Clique em <strong>"Start Graphing"</strong> <br>
      <img src="https://i.imgur.com/UgAXP0l.png" alt="OPS! Imagem não encontrada!"> <br>
      <strong>3</strong> Clique na caixa de texto do lado  superior esquerdo:<br>
      <img src="https://i.imgur.com/dT1oRjx.png" alt="OPS! Imagem não encontrada!"><br>
      <strong>4</strong> Digite : <em>y=ax+b</em><br>
      <img src="https://i.imgur.com/6rgKIYz.png" alt="OPS! Imagem não encontrada!"><br>
      <strong>5</strong> Selecione os controles deslisantes <em>a</em> e <em>b</em><br>
      <img src="https://i.imgur.com/5j7bWtT.png" alt="OPS! Imagem não encontrada!"><br>
      </p>
      <p>Note que você agora tem uma reta!<br>
      Encorajo-o a manipular os controles deslisantantes, e verificar o que ocorre com:<br>
      A reta ao alterar <em>somente</em> o <strong>Coeficiente Linear</strong><br>
      A reta ao alterar <em>Somente</em> o <strong>Coeficiente Angular</strong><br>
      Vamos focar no <strong>Coeficiente Linear</strong> <em>"b"</em><br>
      retorne a os valores dos coeficientes para 1, teremos esse grafico:<br>
      </p>
      <img src="https://i.imgur.com/8kUeEIH.png" alt="OPS! Imagem não encontrada!">
      <p>Agora altere o controle deslisante para 2 e veja o que ocorre</p>
      <img src="https://i.imgur.com/2uVvNjx.png" alt="OPS! Imagem não encontrada!">
      <p>Note que a reta agora cruza o eixo y no valor de 2 <br>
      Altere novamente o controle deslisante para 3 agora<br>onde o você acha que cruzará o eixo das ordenadas?</p>
      <img src="https://i.imgur.com/o5RK19s.png" alt="OPS! Imagem não encontrada!">
      <div class="container">
        <h3>Teste!</h3>
        <p>Qual o valor do <strong>Coenficiente Linear</strong> do gráfico abaixo:</p>
        <img src="https://i.imgur.com/EBLjmSM.png" alt="OPS! Imagem não encontrada!">
        <form method="post">
          {{test1.as_p}}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary">Validar</button>
        </form>
      </div>
      <p>Ótimo! vamos agora manipular o coeficiente angular da reta da seguinte forma:<br>
      <strong>1</strong> retorne os valores para <strong><em>a = 1</em></strong> e <strong><em>b = 0</em></strong>, assim voce terá esse desenho:<br></p>
      <img src="https://i.imgur.com/L4W2NFh.png" alt="OPS! Imagem não encontrada!">
      <p><strong>2</strong> agora troque o valor do <strong><em>a</em></strong> para 2 e você terá o seguinte gráfico:</p>
      <img src="https://i.imgur.com/3AZXtrw.png" alt="OPS! Imagem não encontrada!">
      <p><strong>3</strong> note a diferença na angulação da reta, troque <strong><em>a</em></strong> para 0.5 agora e você tera o gráfico abaixo:</p>
      <img src="https://i.imgur.com/IpiNe2j.png" alt="OPS! Imagem não encontrada!">
      <div class="container">
        <h3>Teste!</h3>
        <p>Você consegue imaginar qual o <strong>Coeficiente Angular</strong> da reta abaixo?:</p>
        <img src="https://i.imgur.com/9zTHV6R.png" alt="OPS! Imagem não encontrada!">
        <form method="post">
          {{test2.as_p}}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary">Validar</button>
        </form>
      </div>
      <h2>Identificando os coeficientes!</h2>
      <p>Agora veremos como identificar os coeficientes da função afim, a partir de seu gráfico!</p>
      <p>Como anteriormente foi visto os coeficientes, você ja deve ter uma noção de como identifica-los <br>
      O mais facil de se encontrar é o <strong><em>coeficiente linear</em></strong>, ele pode ser encontrado substituindo <br>
      a <strong><em>variável independente</em></strong> da função por 0, assim teremos qual o valor da função quando o gráfico <br>
      cruza a <strong><em>imagem</em></strong>, o eixo <strong><em>y</em></strong> no nosso caso.</p>
      <p>Olhe a imagem abaixo:</p>
      <img src="https://i.imgur.com/2uVvNjx.png" alt="OPS! Imagem não encontrada!">
{% endblock %}

Desmo_class/templates/first_app/trigonometria.html
<!DOCTYPE html>
{% extends "first_app/base.html"%}
{% block body_block%}
      <div class="jumbotron">
        <h1>Funções Trigonométricas</h1>
      </div>
{% endblock %}

Desmo_class/templates/first_app/user.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Users</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  </head>
  <body>
    <header>
      <a href="../">Voltar</a>
    </header>
    <div class="container">
      <h1>Faça seu cadastro:</h1>
      <form method="post">
        {{ form.as_p}}
        {% csrf_token %}
        <input type="submit"class="btn btn-primary" value="Enviar">
      </form>
    </div>
  </body>
</html>